---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "startup-forge"
  name: "startup-forge-rmq"
spec:
  selector:
    matchLabels:
      app: "startup-forge-rmq"
  template:
    metadata:
      labels:
        app: "startup-forge-rmq"
    spec:
      containers:
      - name: rabbit
        image: rabbitmq:3.9.16-alpine
        startupProbe:
          exec:
            command: ["rabbitmq-diagnostics", "check_running", "-q"]
          failureThreshold: 30
          periodSeconds: 5
          timeoutSeconds: 10
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS
          value: "guest"
        - name: RABBITMQ_DEFAULT_VHOST
          value: "/"
        resources:
          limits:
            memory: "200Mi"
            cpu: "250m"
        ports:
        - containerPort: 5672
          name: amqp
---
apiVersion: v1
kind: Service
metadata:
  namespace: "startup-forge"
  name: "startup-forge-rmq-service"
spec:
  selector:
    app: "startup-forge-rmq"
  ports:
  - port: 5672
    targetPort: amqp

---
